# Scaffolding generated by Casein v5.0.1.0

module Casein
  class VisitsController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Visits'
  		@visits = Visit.order(sort_order(:visiting_date)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View visit'
      @visit = Visit.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new visit'
    	@visit = Visit.new
    end

    def create
      @visit = Visit.new visit_params
    
      if @visit.save
        flash[:notice] = 'Visit created'
        redirect_to casein_visits_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new visit'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update visit'
      
      @visit = Visit.find params[:id]
    
      if @visit.update_attributes visit_params
        flash[:notice] = 'Visit has been updated'
        redirect_to casein_visits_path
      else
        flash.now[:warning] = 'There were problems when trying to update this visit'
        render :action => :show
      end
    end
 
    def destroy
      @visit = Visit.find params[:id]

      @visit.destroy
      flash[:notice] = 'Visit has been deleted'
      redirect_to casein_visits_path
    end
  
    private
      
      def visit_params
        params.require(:visit).permit(:visiting_date, :concerns_questions, :scheduled_date, :scheduled_time, :notes_comments, :diagnosis_advice, :session_length, :session_balance_due, :session_balance_paid, :overall_balance)
      end

  end
end